name: Upterm Server
version: "1.0.1"
slug: upterm_server
description: "Self-hosted Upterm SSH relay server"
arch:
  - amd64
  - aarch64

host_network: true
startup: services
boot: auto

# Porty zahodíme — u host_network jsou ignorované
ports: {}

map:
  - data:rw

options: {}
schema: {}
